quarkus:
  application:
    name: FIVE
    version: 1.0.0

  http:
    cors:
      ~: true

    port: 8080

  mongodb:
    application-name: FIVE
    connection-string: ${QUARKUS_CONNECTION_STRING:mongodb://falkengrundzyklus:falkengrundzyklus@localhost:27017}
    database: five
